### ISSUE TITLE
Consider using subpackages instead of build strings for pyside2 vs pyqt

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/napari-feedstock#47]
### Comment:

I would like to suggest to use split packages more liberally for the PySide2 vs PyQt5 selection.

I understand the reasons for wanting to install pyqt by default, but the problem right now, is that two packages, that depend on napari, might want to promote different backends for whatever reason.

For example, deeplabcut is using PySide6 by default now.

This could be acheived with:

1. The creation of a `napari-base` package that depends on qtpy letting other applications depend on it.
2. `napari` depending on `napari-base` + other backend.

TBH, I don't really like encouraging build strings for promote PyQt5/PySide2 selection.

They are perfectly safe to install side by side, but today, if one subpackage would like to install napari+pyside2 and an other wants to install napari+pyqt5 they would clash because they would have hard dependencies on different build strings.

the `-base` package resolves things to a large extent.

**Comment by hmaarrfk** [comment]
I'm happy to make a PR for this if this is reasonable

**Comment by hmaarrfk** [comment]
In case one asks, instead of using build strings, you could have:


```
napari   # with different build numbers to depend on one of the two below
napari-pyqt5   # napari-base + pyqt5
napari-pyside2   # napari-base + pyside2
napari-base  # qtpy
```

could help resolve the dependency choice issue.

**Comment by jaimergp** [comment]
I am ok with such a change, but I am failing to see why downstream packages would pin against a runtime choice using the build string instead of signalling that choice via the package explicitly.

IOW, why would I do

```yaml
requirements:
  run:
    - napari * *pyqt*
```

If I can do:

```yaml
requirements:
  run:
    - napari
    - pyqt
```

Has this problem showed up somewhere or is it a hypothetical concern? 

TBH we didn't go through the subpackages way back then because the quirks are a bit messier to explain to maintainers that are not familiar with conda packaging (e.g. top level namespace vs outputs-level namespace, etc).

We might probably need to maintain the build strings because the napari documentation has mentioned them for a while, but I need to check with the maintainers team whether this is that important.

**Comment by hmaarrfk** [comment]
I understand the challenges with packaging choices. I personally don't have a good solution for them either given the on and off and on again commitment toward PySide.

If the dependency on pyqt is removed from some napari package, (be it called base or not) then the two syntaxes, from a package maintainers perspective are the same.

However, today, with specifying a depedency on 

```
requirements:
  run:
    - napari
    - pyside2
```

Would still pull in pyqt5. And while pyqt5 is only a 4MB download, it can have behavioral changes that make it important to take into account.

The practical reason i am bringing this up is that DeepLabCut it has moved to napari from wx. Thus, users have to download, pyside6, and pyqt5. 

I've taken the liberty to patch a few things on the DeepLabCut side to avoid some of this, but it would be good to be able to create a DeepLabCut GUI package that doesn't download both qt5 and qt6 by default.

Tbh, in this version, napari has real bugs that hinder usability so pyside2 cannot be used yet. I've one patch to address some challenges.

**Comment by jaimergp** [comment]
That's reasonable, thanks @hmaarrfk. I'll forward this to the team.

**Comment by Czaki** [comment]
@hmaarrfk Did you notice that none of the released versions of napari supports qt6. We even know bugs that are fixed on main, but not released yet. The problematic places even was not covered by tests, so if you decided to switch to PySide6, then did you perform extensive manual testing before this switch?

We have a plan to release 0.5.0 with experimental support for qt6, and then it should also be reflected in conda-froge recipe

the main argument against this is prevention from plugins depending on the specific backend. 

> Tbh, in this version, napari has real bugs that hinder usability so pyside2 cannot be used yet. I've one patch to address some challenges.

Did you report them? Did there is a problem with a lack of bug fixes or only a lack of release of bugfix?


> However, today, with specifying a depedency on
> 
> ```
> requirements:
>   run:
>     - napari
>     - pyside2
> ```

it looks like a bug in the dependency resolver. @jaimergp Did I'm correct?

**Comment by Czaki** [comment]
And pointed bug applies to both, pyside2 and pyside6. I will ping other core devs to review it to make a decision. For me best option will be PR to `qtpy`. I will open issue there and ask them if they would like to have PR that will unify interfaces.

**Comment by hmaarrfk** [comment]
(Sorry that last message got sent early due to an accidental click) I understand that none of the versions support PySide6.

I am really treating this pyqt/pyside aspect as a long term project.

I am quite sympathetic to the cause that:

```
mamba install napari
```

is a much better user experience than

```
mamba install napari pyqt
```

I would however like to (pre-emptively) avoid package maintainers pinning:

```
requirements:
  run:
     - napari * _*pyqt
```
and an other package pinning:

```
requirements:
  run:
     - napari * _*pyside2
```

this would cause conflicts with very strange resolutions from the user's perspective.


I gave my story regarding PySide6 and DeepLabCut, but you are correct that the pointed to bug affects both PySide2 and PySide6.

Today if two packages have requirements on napari with different build strings, they make the subpackages uninstallable.

PS, there has been a related discussion on some aspects of this in https://github.com/conda-forge/conda-forge.github.io/issues/1770

**Comment by Czaki** [comment]
But even when we split as you suggest then the problem with conflicting backends will persist. 

If someone imports one of Qt backends, then importing the second one will lead to errors or crashes.

The ideal situation for napari will be the have ability to block the installation of any qt backend from plugin manager using conda (I know how to do this for pip). 

Then we could relax politics for conda package as it will not impact less experienced users. 

But this totally requires the opinion of other core devs.

**Comment by hmaarrfk** [comment]
> If someone imports one of Qt backends, then importing the second one will lead to errors or crashes.

This is a problem i am not considering. 

In my opinion, the ability to install packages side by side, and writing code that makes effective use of these packages are two distinct problems.

Maybe the problem is that philosophically, I don't think we should be creating an exclusive relationship between the installation of pyqt5 and pyside2 side by side. (I've linked to a discussion to that effect)

I ma also very sympathetic in limiting the testing surface. Testing, either in a manual way or automated way, for, today,  at least 4 different Qt backbends is a lot of work....

Hopefully you see my comments as constructive.

**Comment by Czaki** [comment]
Did automated test of 4 backends is harder than automated test of 1 backend?

If I correctly remember we have a plan to start dropping Qt5 once Qt6 support becomes stable.

**Comment by aganders3** [comment]
I like this proposal but just have one question. Will plugin authors need to make sure to depend on `napari-base` instead of `napari`?

**Comment by jaimergp** [comment]
For new plugins we will cover that in the staged-recipes review. For existing ones, repodata patches and a bot migration might do it. cc @goanpeca

**Comment by hmaarrfk** [comment]
given that there are many fixes in 0.5.0 for PySide2 (and some 6) compatibility, lets try to target these changes for then? There isn't much of a point in doing it if the application doesn't really start.

**Comment by jni** [comment]
> I like this proposal but just have one question. Will plugin authors need to make sure to depend on napari-base instead of napari?

Oof. I hadn't considered that. In my head I still have plugins not actually depending on napari 😅. Maybe `napari` is `napari-base` and we update our instructions to use `napari-all`? But @jaimergp you don't seem too worried so maybe that's a good enough solution, but it seems like a lot of notification noise again...?

**Comment by goanpeca** [comment]
>In my head I still have plugins not actually depending on napari 😅

Is this still a goal at some point 🤔, I think very few plugin s actually manage to pull this off 😅

**Comment by hmaarrfk** [comment]
The migrations are somewhat painful, and can lead to challenges for older environments, but i think we have tools to help maintainers of plugins with the transition.

**Comment by jni** [comment]
Yeah I agree with you @goanpeca, but my own mindset is slower to change than the world we live in 😂

**Comment by jaimergp** [comment]
We met yesterday and discussed what this change would require, and might want to provide an alternative.

First, our estimated work for the proposed change:

- (1) Create the new output split (`napari-base`, `napari` = `napari-pyqt`, `napari-pyside`).
- (2) Submit a repodata patch to change `napari` to `napari-base` in all packages depending on it.
- (3) Backport (1) to the previous `napari` releases so the change from `napari` to `napari-base` doesn't imply a lower bound constrain on the latest release.
- (4) Add a migrator to go over 250+ feedstocks, and review everything's passing. Even with a high passing rate, this might involve quite manual work.
- (5) Update the currently submitted PRs to `staged-recipes`

That's going to be a long-term effort involving a few hours, "just" to have `napari` not ship `pyqt` or `pyside`.

---

Instead, what if we change how `napari` is distributed, so it mimics the PyPI status a bit more. 

- `napari` would become the hypothetical `napari-base`; aka it won't ship any Qt bindings (but it will have the necessary `run_constrained`). `napari` itself will notify of the missing dependencies with nice messaging if you try to run the GUI.
- Application users would be instructed to `conda install napari pyqt`, or `conda install napari pyside`.
- Other conda packages can just depend on `napari` itself without any changes. We might need to search for packages pinning with a build string but I don't think those would be too many.
- I think we would leave the previous releases untouched to prevent breakages. 

Let me know what you think!

**Comment by Czaki** [comment]
We have code to detect if napari is installed from conda, so it is possible to even adjust the message to installation type.

**Comment by jni** [comment]
I agree with all of the above comments. Thank you all for exploring this! 🙏

**Comment by jaimergp** [comment]
#48 is now available as a preview of how it would look like.
